### ISSUE TITLE
Mesh Slicing Doesn't Work on IOS Build. Index out of Range.

### ISSUE THREAD

**Issue by Happyd4ys** [BLINDED-AM-ME/UnityAssets#11]
First thing great job with Mesh slicing works perfect and very versatile. Only problem is that it works fine in editor but not on IOS build.

Xcode throws error "indexOutOfRangeException: Array index is out of range.
  at BLINDED_AM_ME.MeshCut.Cut (UnityEngine.GameObject victim, Vector3 anchorPoint, Vector3 normalDirection, UnityEngine.Material capMaterial)" 

I funneled down the problem to AddTriangle (_leftSide.AddTriangle()). It occurs when an imported asset is sliced. Funny thing is that it works perfectly in editor but throws an error on build. I tried fixing it myself but not the best at mesh generation. 

`_leftSide.AddTriangle(
                                new Vector3[] { _victim_mesh.vertices[p1], _victim_mesh.vertices[p2], _victim_mesh.vertices[p3] },
                                new Vector3[] { _victim_mesh.normals[p1], _victim_mesh.normals[p2], _victim_mesh.normals[p3] },
                                new Vector2[] { _victim_mesh.uv[p1], _victim_mesh.uv[p2], _victim_mesh.uv[p3] },
                                new Vector4[] { _victim_mesh.tangents[p1], _victim_mesh.tangents[p2], _victim_mesh.tangents[p3] },
                                sub);`

Any clue what the issue is?

**Comment by MjenHart** [comment]
Hey I modified the code to ignore model uv's and tangents, for me, this works perfectly now:

[MeshCut.zip](https://github.com/BLINDED-AM-ME/UnityAssets/files/3138769/MeshCut.zip)
[MeshMaker.zip](https://github.com/BLINDED-AM-ME/UnityAssets/files/3138771/MeshMaker.zip)

**Comment by Happyd4ys** [comment]
Thanks works great for my purpose as-well. Great job and you taught me something :)

**Comment by Pimeko** [comment]
I made it work by simply **commenting** these 3 lines in MeshCut.cs, lines 103-106 : 

```c#
_triangleCache.tangents[0] = mesh_tangents[index_1];
_triangleCache.tangents[1] = mesh_tangents[index_2];
_triangleCache.tangents[2] = mesh_tangents[index_3];
```

It works like a charm now :)

**Comment by BLINDED-AM-ME** [comment]
Thanks, I will put in some checks for if it has tangents.
