### ISSUE TITLE
Mesh Cut problem.

### ISSUE THREAD

**Issue by werto165** [BLINDED-AM-ME/UnityAssets#4]
the code that makes the cut has a bug in / omission. it's to do with the local scale: 

GameObject rightSideObj = new GameObject("right side", typeof(MeshFilter), typeof(MeshRenderer));
			rightSideObj.transform.position = victim.transform.position;
			rightSideObj.transform.rotation = victim.transform.rotation;
        

    rightSideObj.transform.localScale = victim.transform.localScale; this line is needed if you change the geometries scale from the default of 1,1,1.

**Comment by BLINDED-AM-ME** [comment]
The original version didn't handle different scales right. You still need the scale of the victim to have the xyz values equal the same. (1,1,1) (0.5,0.5,0.5) (2,2,2) and so on.

added to the 2017-07-01 package

```
if(victim.transform.parent != null){
         rightSideObj.transform.parent = victim.transform.parent;
}

	rightSideObj.transform.localScale = victim.transform.localScale;
```
