### ISSUE TITLE
Lack of particle system prewarm

### ISSUE THREAD

**Issue by indevMioss** [BLINDED-AM-ME/UnityAssets#5]
We are currently using your asset, really nice work by the way. Unity surely lacks this functionality at the moment.
Anyway, we miss particle system presimulation badly. It's an important thing when you deal with long trajectories and slow particles. 
E.g: using your system for water flow simulation we have to wait circa 20 second until particles going all the way along the trajectory. In that case prewarm functionality is critical.

We would also appreciate any advice for fast solving this issue, even if it's gonna be a dirty way.
Thanks in advance.

**Comment by BLINDED-AM-ME** [comment]
I looked into it
you can add this code to
ParticlePathFlow.cs at line 102 in the OnEnable function
```
if(_particle_system.main.prewarm){
        float numRevive = Mathf.Floor(emissionRate * _particle_system.main.startLifetime.constant);
        for(int i=0; i<numRevive; i++){
                _particle_trackerArray[i].Revive(_particle_system);
                _particle_trackerArray[i].particle.remainingLifetime = 
                _particle_trackerArray[i].particle.startLifetime * ((float)i/numRevive);
        }
}
```
