### ISSUE TITLE
Movement not working in build

### ISSUE THREAD

**Issue by AndreaPara** [BLINDED-AM-ME/UnityAssets#6]
Hello, I tried to contact you by email but I couldn't find a way to do so.
I am using the particle path flow and everything works in the editor.
I need one of the points in the path to be moved according to the position of another moving object at runtime. 
In this way, it seems like the flow of particles follows that object at runtime.
But it seems like the points of the path can be moved at runtime only inside of the editor, not in the build. 

It could be a nice feature in general, and a good improvement to the package.
Regards

**Comment by BLINDED-AM-ME** [comment]
I rewrote it to give more power to the particle system.
I added a variable isPathUpdating to update the path each frame.
