### ISSUE TITLE
Lag in mesh cut

### ISSUE THREAD

**Issue by abhidec1** [BLINDED-AM-ME/UnityAssets#7]
Hi ,

Great asset , wanted to let you know that i noticed there is an increase in lag with every cut. For example , lag is hardly noticeable during first 5-6 cuts , after that it starts freezing for split second .

**Comment by Bakar112** [comment]
Hi, abhidec1
Can you find any solution for the lag?
Thanks

**Comment by abhidec1** [comment]
> Hi, abhidec1
> Can you find any solution for the lag?
> Thanks

nope i didnt . In my case i was slicing a tall cylinder , so instead of slicing same mesh again and again i made the cylinder by placing small cylinders on top of each other. Every slice was made on separate mesh and later on both chunks were removed from scene . That solved the lag issue for me.
